import Head from "next/head";
import HomeComponent from "../components/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Orphan Breath Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-txtColor bg-bgColor pb-5">
        <HomeComponent />
      </main>
    </>
  );
}
