import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Orphan Breath Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900 max-h-screen h-screen flex items-center justify-center text-white">
        <h1 className="">orphanbreathfoundation</h1>
      </main>
    </div>
  );
}
