import Head from "next/head";
import styles from "../styles/Global";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Orphan Breath Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`text-txtColor bg-bgColor py-20 flex flex-col gap-10 items-center min-h-screen justify-center`}>
        <h1 className="headingFont">Orphan Breath Foundation</h1>

        <a class="btn btn-primary">Button</a>

        
      </main>
    </div>
  );
}
